### ISSUE TITLE
Performance optimization for Doctrine Query

### ISSUE THREAD

**Issue by JHGitty** [craue/CraueGeoBundle#9] opened 2015-08-22 15:45 UTC
You should look at this:
http://de.scribd.com/doc/2569355/Geo-Distance-Search-with-MySQL

There is explained a way to get better performance.

Is this performance boost integrated into this bundle?

**Comment by craue** [comment] 2015-08-24 08:00
duplicate of #5

**Closed by craue** 2015-08-24 08:00 UTC
